name: Weekly Lead Digest

on:
  schedule:
    # Runs every Monday at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  send-digest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install requests pandas
    
    - name: Run email digest script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        python email_digest.py
